# Environments
development:
  adapter: mysql2
  database: tlogs_development
  username: root
  password:
  encoding: UTF8
  host: localhost

test:
  adapter: mysql2
  database: tlogs_test 
  username: root
  password:
  encoding: UTF8
  host: localhost

production:
  adapter: mysql2
  database: tlogs_development
  username: root
  password: 
  encoding: UTF8
  host: localhost
